apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:fzozyurt/gitOps-test.git
    targetRevision: HEAD
    path: manifests
    sshPrivateKeySecret:
      name: argocd-ssh
      key: ssh-privatekey
  syncPolicy:
    automated: {}
  destination:
    namespace: default
    server: https://kubernetes.default.svc